# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_generation/stored_map_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensor_data import gnss_data_pb2 as sensor__data_dot_gnss__data__pb2
from sensor_data import imu_data_pb2 as sensor__data_dot_imu__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='map_generation/stored_map_data.proto',
  package='meercat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$map_generation/stored_map_data.proto\x12\x07meercat\x1a\x1bsensor_data/gnss_data.proto\x1a\x1asensor_data/imu_data.proto\"g\n\x0fStored_Map_Data\x12\"\n\x04gnss\x18\x02 \x01(\x0b\x32\x12.meercat.GNSS_DataH\x00\x12 \n\x03imu\x18\x03 \x01(\x0b\x32\x11.meercat.IMU_DataH\x00\x42\x0e\n\x0csensor_oneofb\x06proto3'
  ,
  dependencies=[sensor__data_dot_gnss__data__pb2.DESCRIPTOR,sensor__data_dot_imu__data__pb2.DESCRIPTOR,])




_STORED_MAP_DATA = _descriptor.Descriptor(
  name='Stored_Map_Data',
  full_name='meercat.Stored_Map_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gnss', full_name='meercat.Stored_Map_Data.gnss', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu', full_name='meercat.Stored_Map_Data.imu', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sensor_oneof', full_name='meercat.Stored_Map_Data.sensor_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=106,
  serialized_end=209,
)

_STORED_MAP_DATA.fields_by_name['gnss'].message_type = sensor__data_dot_gnss__data__pb2._GNSS_DATA
_STORED_MAP_DATA.fields_by_name['imu'].message_type = sensor__data_dot_imu__data__pb2._IMU_DATA
_STORED_MAP_DATA.oneofs_by_name['sensor_oneof'].fields.append(
  _STORED_MAP_DATA.fields_by_name['gnss'])
_STORED_MAP_DATA.fields_by_name['gnss'].containing_oneof = _STORED_MAP_DATA.oneofs_by_name['sensor_oneof']
_STORED_MAP_DATA.oneofs_by_name['sensor_oneof'].fields.append(
  _STORED_MAP_DATA.fields_by_name['imu'])
_STORED_MAP_DATA.fields_by_name['imu'].containing_oneof = _STORED_MAP_DATA.oneofs_by_name['sensor_oneof']
DESCRIPTOR.message_types_by_name['Stored_Map_Data'] = _STORED_MAP_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stored_Map_Data = _reflection.GeneratedProtocolMessageType('Stored_Map_Data', (_message.Message,), {
  'DESCRIPTOR' : _STORED_MAP_DATA,
  '__module__' : 'map_generation.stored_map_data_pb2'
  # @@protoc_insertion_point(class_scope:meercat.Stored_Map_Data)
  })
_sym_db.RegisterMessage(Stored_Map_Data)


# @@protoc_insertion_point(module_scope)
