# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_data/imu_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor_data/imu_data.proto',
  package='meercat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asensor_data/imu_data.proto\x12\x07meercat\"\xa1\x03\n\x08IMU_Data\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12\x39\n\x0clinear_accel\x18\x02 \x01(\x0b\x32#.meercat.IMU_Data.Linear_Accel_Data\x12/\n\x07\x61ng_vel\x18\x03 \x01(\x0b\x32\x1e.meercat.IMU_Data.Ang_Vel_Data\x12/\n\x07rot_vec\x18\x04 \x01(\x0b\x32\x1e.meercat.IMU_Data.Rot_Vec_Data\x1a\x46\n\x11Linear_Accel_Data\x12\x0f\n\x07\x61\x63\x63\x65l_x\x18\x01 \x01(\x01\x12\x0f\n\x07\x61\x63\x63\x65l_y\x18\x02 \x01(\x01\x12\x0f\n\x07\x61\x63\x63\x65l_z\x18\x03 \x01(\x01\x1aG\n\x0c\x41ng_Vel_Data\x12\x11\n\tang_vel_x\x18\x01 \x01(\x01\x12\x11\n\tang_vel_y\x18\x02 \x01(\x01\x12\x11\n\tang_vel_z\x18\x03 \x01(\x01\x1aQ\n\x0cRot_Vec_Data\x12\x0e\n\x06quat_i\x18\x01 \x01(\x01\x12\x0e\n\x06quat_j\x18\x02 \x01(\x01\x12\x0e\n\x06quat_k\x18\x03 \x01(\x01\x12\x11\n\tquat_real\x18\x04 \x01(\x01\x62\x06proto3'
)




_IMU_DATA_LINEAR_ACCEL_DATA = _descriptor.Descriptor(
  name='Linear_Accel_Data',
  full_name='meercat.IMU_Data.Linear_Accel_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accel_x', full_name='meercat.IMU_Data.Linear_Accel_Data.accel_x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accel_y', full_name='meercat.IMU_Data.Linear_Accel_Data.accel_y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accel_z', full_name='meercat.IMU_Data.Linear_Accel_Data.accel_z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=301,
)

_IMU_DATA_ANG_VEL_DATA = _descriptor.Descriptor(
  name='Ang_Vel_Data',
  full_name='meercat.IMU_Data.Ang_Vel_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ang_vel_x', full_name='meercat.IMU_Data.Ang_Vel_Data.ang_vel_x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ang_vel_y', full_name='meercat.IMU_Data.Ang_Vel_Data.ang_vel_y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ang_vel_z', full_name='meercat.IMU_Data.Ang_Vel_Data.ang_vel_z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=374,
)

_IMU_DATA_ROT_VEC_DATA = _descriptor.Descriptor(
  name='Rot_Vec_Data',
  full_name='meercat.IMU_Data.Rot_Vec_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quat_i', full_name='meercat.IMU_Data.Rot_Vec_Data.quat_i', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quat_j', full_name='meercat.IMU_Data.Rot_Vec_Data.quat_j', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quat_k', full_name='meercat.IMU_Data.Rot_Vec_Data.quat_k', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quat_real', full_name='meercat.IMU_Data.Rot_Vec_Data.quat_real', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=457,
)

_IMU_DATA = _descriptor.Descriptor(
  name='IMU_Data',
  full_name='meercat.IMU_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_ms', full_name='meercat.IMU_Data.timestamp_ms', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_accel', full_name='meercat.IMU_Data.linear_accel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ang_vel', full_name='meercat.IMU_Data.ang_vel', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rot_vec', full_name='meercat.IMU_Data.rot_vec', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IMU_DATA_LINEAR_ACCEL_DATA, _IMU_DATA_ANG_VEL_DATA, _IMU_DATA_ROT_VEC_DATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=457,
)

_IMU_DATA_LINEAR_ACCEL_DATA.containing_type = _IMU_DATA
_IMU_DATA_ANG_VEL_DATA.containing_type = _IMU_DATA
_IMU_DATA_ROT_VEC_DATA.containing_type = _IMU_DATA
_IMU_DATA.fields_by_name['linear_accel'].message_type = _IMU_DATA_LINEAR_ACCEL_DATA
_IMU_DATA.fields_by_name['ang_vel'].message_type = _IMU_DATA_ANG_VEL_DATA
_IMU_DATA.fields_by_name['rot_vec'].message_type = _IMU_DATA_ROT_VEC_DATA
DESCRIPTOR.message_types_by_name['IMU_Data'] = _IMU_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IMU_Data = _reflection.GeneratedProtocolMessageType('IMU_Data', (_message.Message,), {

  'Linear_Accel_Data' : _reflection.GeneratedProtocolMessageType('Linear_Accel_Data', (_message.Message,), {
    'DESCRIPTOR' : _IMU_DATA_LINEAR_ACCEL_DATA,
    '__module__' : 'sensor_data.imu_data_pb2'
    # @@protoc_insertion_point(class_scope:meercat.IMU_Data.Linear_Accel_Data)
    })
  ,

  'Ang_Vel_Data' : _reflection.GeneratedProtocolMessageType('Ang_Vel_Data', (_message.Message,), {
    'DESCRIPTOR' : _IMU_DATA_ANG_VEL_DATA,
    '__module__' : 'sensor_data.imu_data_pb2'
    # @@protoc_insertion_point(class_scope:meercat.IMU_Data.Ang_Vel_Data)
    })
  ,

  'Rot_Vec_Data' : _reflection.GeneratedProtocolMessageType('Rot_Vec_Data', (_message.Message,), {
    'DESCRIPTOR' : _IMU_DATA_ROT_VEC_DATA,
    '__module__' : 'sensor_data.imu_data_pb2'
    # @@protoc_insertion_point(class_scope:meercat.IMU_Data.Rot_Vec_Data)
    })
  ,
  'DESCRIPTOR' : _IMU_DATA,
  '__module__' : 'sensor_data.imu_data_pb2'
  # @@protoc_insertion_point(class_scope:meercat.IMU_Data)
  })
_sym_db.RegisterMessage(IMU_Data)
_sym_db.RegisterMessage(IMU_Data.Linear_Accel_Data)
_sym_db.RegisterMessage(IMU_Data.Ang_Vel_Data)
_sym_db.RegisterMessage(IMU_Data.Rot_Vec_Data)


# @@protoc_insertion_point(module_scope)
