# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wombat_interchange/wombat_cmd_msg.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wombat_interchange/wombat_cmd_msg.proto',
  package='meercat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'wombat_interchange/wombat_cmd_msg.proto\x12\x07meercat\"7\n$WombatGetFullMapSequenceMsgs_Payload\x12\x0f\n\x07map_num\x18\x01 \x01(\r\"M\n\"WombatRepeatMapSequenceMsg_Payload\x12\x0f\n\x07map_num\x18\x01 \x01(\r\x12\x16\n\x0erepeat_seq_num\x18\x02 \x01(\r\"\xc1\x01\n\x0cWombatCmdMsg\x12(\n\x08\x63md_enum\x18\x01 \x01(\x0e\x32\x16.meercat.WombatCmdEnum\x12=\n\x04\x66ull\x18\x02 \x01(\x0b\x32-.meercat.WombatGetFullMapSequenceMsgs_PayloadH\x00\x12=\n\x06repeat\x18\x03 \x01(\x0b\x32+.meercat.WombatRepeatMapSequenceMsg_PayloadH\x00\x42\t\n\x07payload*\x87\x01\n\rWombatCmdEnum\x12\x1c\n\x18START_SENSOR_UPDATE_MODE\x10\x00\x12\x1b\n\x17STOP_SENSOR_UPDATE_MODE\x10\x01\x12\x1e\n\x1aGET_FULL_MAP_SEQUENCE_MSGS\x10\x02\x12\x1b\n\x17REPEAT_MAP_SEQUENCE_MSG\x10\x03\x62\x06proto3'
)

_WOMBATCMDENUM = _descriptor.EnumDescriptor(
  name='WombatCmdEnum',
  full_name='meercat.WombatCmdEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START_SENSOR_UPDATE_MODE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP_SENSOR_UPDATE_MODE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GET_FULL_MAP_SEQUENCE_MSGS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPEAT_MAP_SEQUENCE_MSG', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=385,
  serialized_end=520,
)
_sym_db.RegisterEnumDescriptor(_WOMBATCMDENUM)

WombatCmdEnum = enum_type_wrapper.EnumTypeWrapper(_WOMBATCMDENUM)
START_SENSOR_UPDATE_MODE = 0
STOP_SENSOR_UPDATE_MODE = 1
GET_FULL_MAP_SEQUENCE_MSGS = 2
REPEAT_MAP_SEQUENCE_MSG = 3



_WOMBATGETFULLMAPSEQUENCEMSGS_PAYLOAD = _descriptor.Descriptor(
  name='WombatGetFullMapSequenceMsgs_Payload',
  full_name='meercat.WombatGetFullMapSequenceMsgs_Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_num', full_name='meercat.WombatGetFullMapSequenceMsgs_Payload.map_num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=107,
)


_WOMBATREPEATMAPSEQUENCEMSG_PAYLOAD = _descriptor.Descriptor(
  name='WombatRepeatMapSequenceMsg_Payload',
  full_name='meercat.WombatRepeatMapSequenceMsg_Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_num', full_name='meercat.WombatRepeatMapSequenceMsg_Payload.map_num', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeat_seq_num', full_name='meercat.WombatRepeatMapSequenceMsg_Payload.repeat_seq_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=186,
)


_WOMBATCMDMSG = _descriptor.Descriptor(
  name='WombatCmdMsg',
  full_name='meercat.WombatCmdMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_enum', full_name='meercat.WombatCmdMsg.cmd_enum', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full', full_name='meercat.WombatCmdMsg.full', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='repeat', full_name='meercat.WombatCmdMsg.repeat', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='meercat.WombatCmdMsg.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=189,
  serialized_end=382,
)

_WOMBATCMDMSG.fields_by_name['cmd_enum'].enum_type = _WOMBATCMDENUM
_WOMBATCMDMSG.fields_by_name['full'].message_type = _WOMBATGETFULLMAPSEQUENCEMSGS_PAYLOAD
_WOMBATCMDMSG.fields_by_name['repeat'].message_type = _WOMBATREPEATMAPSEQUENCEMSG_PAYLOAD
_WOMBATCMDMSG.oneofs_by_name['payload'].fields.append(
  _WOMBATCMDMSG.fields_by_name['full'])
_WOMBATCMDMSG.fields_by_name['full'].containing_oneof = _WOMBATCMDMSG.oneofs_by_name['payload']
_WOMBATCMDMSG.oneofs_by_name['payload'].fields.append(
  _WOMBATCMDMSG.fields_by_name['repeat'])
_WOMBATCMDMSG.fields_by_name['repeat'].containing_oneof = _WOMBATCMDMSG.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['WombatGetFullMapSequenceMsgs_Payload'] = _WOMBATGETFULLMAPSEQUENCEMSGS_PAYLOAD
DESCRIPTOR.message_types_by_name['WombatRepeatMapSequenceMsg_Payload'] = _WOMBATREPEATMAPSEQUENCEMSG_PAYLOAD
DESCRIPTOR.message_types_by_name['WombatCmdMsg'] = _WOMBATCMDMSG
DESCRIPTOR.enum_types_by_name['WombatCmdEnum'] = _WOMBATCMDENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WombatGetFullMapSequenceMsgs_Payload = _reflection.GeneratedProtocolMessageType('WombatGetFullMapSequenceMsgs_Payload', (_message.Message,), {
  'DESCRIPTOR' : _WOMBATGETFULLMAPSEQUENCEMSGS_PAYLOAD,
  '__module__' : 'wombat_interchange.wombat_cmd_msg_pb2'
  # @@protoc_insertion_point(class_scope:meercat.WombatGetFullMapSequenceMsgs_Payload)
  })
_sym_db.RegisterMessage(WombatGetFullMapSequenceMsgs_Payload)

WombatRepeatMapSequenceMsg_Payload = _reflection.GeneratedProtocolMessageType('WombatRepeatMapSequenceMsg_Payload', (_message.Message,), {
  'DESCRIPTOR' : _WOMBATREPEATMAPSEQUENCEMSG_PAYLOAD,
  '__module__' : 'wombat_interchange.wombat_cmd_msg_pb2'
  # @@protoc_insertion_point(class_scope:meercat.WombatRepeatMapSequenceMsg_Payload)
  })
_sym_db.RegisterMessage(WombatRepeatMapSequenceMsg_Payload)

WombatCmdMsg = _reflection.GeneratedProtocolMessageType('WombatCmdMsg', (_message.Message,), {
  'DESCRIPTOR' : _WOMBATCMDMSG,
  '__module__' : 'wombat_interchange.wombat_cmd_msg_pb2'
  # @@protoc_insertion_point(class_scope:meercat.WombatCmdMsg)
  })
_sym_db.RegisterMessage(WombatCmdMsg)


# @@protoc_insertion_point(module_scope)
